baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Clio Blog'
theme = 'ananke'
contentDir = "content"

[params]
  mainSections = ["posts"]

[taxonomies]
  category = "categories"
  tag = "tags"
